### PR TITLE
Fix outdated dependencies, fix tests

### PR DESCRIPTION
**Pull request by jrrbru**

### CODE REVIEW

**Comment by jrrbru** [comment]
@twhitbeck can you please clone this repo/branch and run `grunt testRhino`? I don't think that test works on Windows.

**Comment by twhitbeck** [comment]
got the following errors when running `grunt testRhino`

```
Running "execute:testRhino" (execute) task
-> executing /home/tim/src/github.com/wombatsecurity/dustjs/node_modules/.bin/rhino1_7r3
Running unit tests with /home/tim/src/github.com/wombatsecurity/dustjs/node_modules/rhino-1_7r3-bin/rhino1_7R3/js.jar
Exception in thread "Thread-1" org.mozilla.javascript.EvaluatorException: Can't find method java.lang.Thread.sleep(org.mozilla.javascript.Undefined).
        at org.mozilla.javascript.tools.ToolErrorReporter.runtimeError(ToolErrorReporter.java:144)
        at org.mozilla.javascript.Context.reportRuntimeError(Context.java:945)
        at org.mozilla.javascript.Context.reportRuntimeError(Context.java:1001)
        at org.mozilla.javascript.Context.reportRuntimeError1(Context.java:964)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:166)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
        at org.mozilla.javascript.gen.test_lib_rhino_bootstrap_js_3._c_anonymous_5(Unknown Source)
        at org.mozilla.javascript.gen.test_lib_rhino_bootstrap_js_3.call(Unknown Source)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3178)
        at org.mozilla.javascript.gen.test_lib_rhino_bootstrap_js_3.call(Unknown Source)
        at org.mozilla.javascript.Context$1.run(Context.java:510)
        at org.mozilla.javascript.Context.call(Context.java:521)
        at org.mozilla.javascript.Context.call(Context.java:508)
        at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:568)
        at adapter1.run(<adapter>)
        at java.base/java.lang.Thread.run(Thread.java:834)
-> completed /home/tim/src/github.com/wombatsecurity/dustjs/node_modules/.bin/rhino1_7r3 (977ms)
-> executing /home/tim/src/github.com/wombatsecurity/dustjs/node_modules/.bin/rhino1_7r5
Running unit tests with /home/tim/src/github.com/wombatsecurity/dustjs/node_modules/rhino-1_7r5-bin/rhino1_7R5/js.jar
Exception in thread "Thread-1" org.mozilla.javascript.EvaluatorException: Can't find method java.lang.Thread.sleep(org.mozilla.javascript.Undefined).
        at org.mozilla.javascript.tools.ToolErrorReporter.runtimeError(ToolErrorReporter.java:111)
        at org.mozilla.javascript.Context.reportRuntimeError(Context.java:913)
        at org.mozilla.javascript.Context.reportRuntimeError(Context.java:969)
        at org.mozilla.javascript.Context.reportRuntimeError1(Context.java:932)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:144)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at org.mozilla.javascript.gen.test_lib_rhino_bootstrap_js_3._c_anonymous_5(Unknown Source)
        at org.mozilla.javascript.gen.test_lib_rhino_bootstrap_js_3.call(Unknown Source)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
        at org.mozilla.javascript.gen.test_lib_rhino_bootstrap_js_3.call(Unknown Source)
        at org.mozilla.javascript.Context$1.run(Context.java:478)
        at org.mozilla.javascript.Context.call(Context.java:489)
        at org.mozilla.javascript.Context.call(Context.java:476)
        at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:576)
        at adapter1.run(<adapter>)
        at java.base/java.lang.Thread.run(Thread.java:834)
-> completed /home/tim/src/github.com/wombatsecurity/dustjs/node_modules/.bin/rhino1_7r5 (924ms)
```

Running with Java 11:
```
$ java --version
openjdk 11.0.5-ea 2019-10-15
OpenJDK Runtime Environment (build 11.0.5-ea+10-post-Ubuntu-0ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.5-ea+10-post-Ubuntu-0ubuntu1, mixed mode, sharing)
```

**Comment by jrrbru** [comment]
Okay, I've removed Rhino because it appears that we don't need it - it's an outdated Java implementation of a JavaScript engine. Can you do a run through the PR and see if there's anything else you want to check out?

**Comment by twhitbeck** [comment]
sure

**Pull request merged**
